name: Clone to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Execute git clone on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/www/temp_builder/${{ github.event.repository.name }}/clone
            git clone ${{ github.event.repository.clone_url }}
            mv ./* ../
            cd ..
            npm i
            npm run build
            mv build package.json node_modules ~/www/netflux/
            rm -rf clone/*
